import pandas as pd
import numpy as np
from typing import Dict, Tuple
from core.base_features import BaseFeatureEngineer

class HybridFeatureEngineer(BaseFeatureEngineer):
    EPSILON = 1e-8
    
    def process(self, cleaned_datasets: Dict[str, pd.DataFrame]) -> Tuple[Dict[str, pd.DataFrame], int]:
        feature_datasets = {}
        
        for split_name, df in cleaned_datasets.items():
            print(f"Engineering features for {split_name} split...")
            
            # Ensure sorting to prevent look-ahead bias
            df = df.sort_values(['ticker', 'date']).copy()
            
            # Create a base dataframe to hold the new features
            feat_df = df[['ticker', 'date']].copy()
            
            # Calculate market proxy safely
            df['temp_ret'] = df.groupby('ticker')['close'].pct_change().fillna(0.0)
            market_proxy = df.groupby('date')['temp_ret'].mean().reset_index(name='mkt_ret')
            df = pd.merge(df, market_proxy, on='date', how='left')

            # Dynamically dispatch calculations
            for feature in self.features_list:
                method_name = f"_calc_{feature}"
                if hasattr(self, method_name):
                    method = getattr(self, method_name)
                    feat_df[feature] = method(df)
                else:
                    raise NotImplementedError(f"Feature '{feature}' is not implemented in {self.__class__.__name__}")
            
            # Scrub mathematical anomalies (Inf / -Inf -> NaN) before dropping
            feat_df[self.features_list] = feat_df[self.features_list].replace([np.inf, -np.inf], np.nan)
            
            # Drop NaNs generated by rolling windows (e.g., first 50 days for SMA_50)
            original_len = len(feat_df)
            feat_df.dropna(inplace=True)
            feat_df.reset_index(drop=True, inplace=True)
            
            # Failsafe: If any residual NaNs remain after dropna, fill with 0.0
            feat_df[self.features_list] = feat_df[self.features_list].fillna(0.0)
            
            nan_count = feat_df.isna().sum().sum()
            print(f"  -> {split_name} features built. Dropped {original_len - len(feat_df)} warmup rows. Total NaNs: {nan_count}")
            assert nan_count == 0, f"Critical Error: Feature Matrix ({split_name}) contains {nan_count} NaNs!"
            
            feature_datasets[split_name] = feat_df

        feature_dim = len(self.features_list)
        return feature_datasets, feature_dim

    # ==========================================
    # 1. RAW MARKET
    # ==========================================
    def _calc_open(self, df): return df['open']
    def _calc_high(self, df): return df['high']
    def _calc_low(self, df): return df['low']
    def _calc_close(self, df): return df['close']
    def _calc_volume(self, df): return df['volume']

    # ==========================================
    # 2. PRICE FEATURES
    # ==========================================
    def _calc_log_return(self, df):
        prev_close = df.groupby('ticker')['close'].shift(1).replace(0, self.EPSILON)
        return np.log(np.maximum(df['close'], self.EPSILON) / prev_close).fillna(0.0)
    
    def _calc_high_low_pct(self, df):
        return (df['high'] - df['low']) / (df['close'] + self.EPSILON)
        
    def _calc_open_close_pct(self, df):
        return (df['close'] - df['open']) / (df['open'] + self.EPSILON)
        
    def _calc_gap_pct(self, df):
        prev_close = df.groupby('ticker')['close'].shift(1).replace(0, self.EPSILON)
        return (df['open'] - prev_close) / prev_close

    # ==========================================
    # 3. TREND FEATURES
    # ==========================================
    def _calc_sma_10(self, df):
        return df.groupby('ticker')['close'].transform(lambda x: x.rolling(10).mean())
        
    def _calc_sma_20(self, df):
        return df.groupby('ticker')['close'].transform(lambda x: x.rolling(20).mean())
        
    def _calc_ema_20(self, df):
        return df.groupby('ticker')['close'].transform(lambda x: x.ewm(span=20, adjust=False).mean())
        
    def _calc_dist_sma_20(self, df):
        sma_20 = self._calc_sma_20(df)
        return (df['close'] - sma_20) / (sma_20 + self.EPSILON)
        
    def _calc_sma_20_50_cross(self, df):
        sma_20 = self._calc_sma_20(df)
        sma_50 = df.groupby('ticker')['close'].transform(lambda x: x.rolling(50).mean())
        return sma_20 - sma_50

    # ==========================================
    # 4. VOLATILITY FEATURES
    # ==========================================
    def _calc_rolling_std_20(self, df):
        rets = df.groupby('ticker')['close'].pct_change().fillna(0.0)
        return rets.groupby(df['ticker']).transform(lambda x: x.rolling(20).std()).fillna(0.0)
        
    def _calc_atr_14(self, df):
        prev_close = df.groupby('ticker')['close'].shift(1)
        tr1 = df['high'] - df['low']
        tr2 = (df['high'] - prev_close).abs()
        tr3 = (df['low'] - prev_close).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        return tr.groupby(df['ticker']).transform(lambda x: x.rolling(14).mean()).fillna(0.0)

    def _calc_parkinson_vol_20(self, df):
        high_safe = np.maximum(df['high'], self.EPSILON)
        low_safe = np.maximum(df['low'], self.EPSILON)
        log_hl = np.log(high_safe / low_safe) ** 2
        factor = 1 / (4 * np.log(2))
        return np.sqrt(factor * log_hl.groupby(df['ticker']).transform(lambda x: x.rolling(20).mean())).fillna(0.0)

    def _calc_bb_width_20(self, df):
        sma = self._calc_sma_20(df)
        std = df.groupby('ticker')['close'].transform(lambda x: x.rolling(20).std()).fillna(0.0)
        return (4 * std) / (sma + self.EPSILON)

    # ==========================================
    # 5. MOMENTUM FEATURES
    # ==========================================
    def _calc_rsi_14(self, df):
        delta = df.groupby('ticker')['close'].diff()
        gain = delta.clip(lower=0)
        loss = -1 * delta.clip(upper=0)
        avg_gain = gain.groupby(df['ticker']).transform(lambda x: x.rolling(14).mean()).fillna(0.0)
        avg_loss = loss.groupby(df['ticker']).transform(lambda x: x.rolling(14).mean()).fillna(0.0)
        rs = avg_gain / (avg_loss + self.EPSILON)
        return 100 - (100 / (1 + rs))

    def _calc_macd(self, df):
        ema_12 = df.groupby('ticker')['close'].transform(lambda x: x.ewm(span=12, adjust=False).mean())
        ema_26 = df.groupby('ticker')['close'].transform(lambda x: x.ewm(span=26, adjust=False).mean())
        return ema_12 - ema_26

    def _calc_macd_hist(self, df):
        macd = self._calc_macd(df)
        macd_signal = macd.groupby(df['ticker']).transform(lambda x: x.ewm(span=9, adjust=False).mean())
        return macd - macd_signal

    def _calc_momentum_10(self, df):
        return (df['close'] - df.groupby('ticker')['close'].shift(10)).fillna(0.0)

    # ==========================================
    # 6. VOLUME FEATURES
    # ==========================================
    def _calc_vol_ma_ratio_20(self, df):
        vol_ma = df.groupby('ticker')['volume'].transform(lambda x: x.rolling(20).mean())
        return df['volume'] / (vol_ma + self.EPSILON)

    def _calc_obv(self, df):
        direction = np.sign(df.groupby('ticker')['close'].diff().fillna(0.0))
        return (direction * df['volume']).groupby(df['ticker']).cumsum()

    # ==========================================
    # 7. STATISTICAL FEATURES
    # ==========================================
    def _calc_skewness_20(self, df):
        rets = df.groupby('ticker')['close'].pct_change().fillna(0.0)
        return rets.groupby(df['ticker']).transform(lambda x: x.rolling(20).skew()).fillna(0.0)

    def _calc_kurtosis_20(self, df):
        rets = df.groupby('ticker')['close'].pct_change().fillna(0.0)
        return rets.groupby(df['ticker']).transform(lambda x: x.rolling(20).kurt()).fillna(0.0)

    def _calc_hurst_proxy_20(self, df):
        roll_min = df.groupby('ticker')['close'].transform(lambda x: x.rolling(20).min())
        roll_max = df.groupby('ticker')['close'].transform(lambda x: x.rolling(20).max())
        return (df['close'] - roll_min) / (roll_max - roll_min + self.EPSILON)

    def _calc_autocorr_lag1_20(self, df):
        rets = df.groupby('ticker')['close'].pct_change().fillna(0.0)
        return rets.groupby(df['ticker']).transform(lambda x: x.rolling(20).apply(lambda s: s.autocorr(1), raw=False)).fillna(0.0)

    # ==========================================
    # 8. MARKET CONTEXT
    # ==========================================
    def _calc_market_return(self, df):
        return df['mkt_ret'].fillna(0.0)

    def _calc_rolling_beta_20(self, df):
        rets = df.groupby('ticker')['close'].pct_change().fillna(0.0)
        cov = rets.groupby(df['ticker']).transform(lambda x: x.rolling(20).cov(df['mkt_ret'])).fillna(0.0)
        mkt_var = df.groupby('ticker')['mkt_ret'].transform(lambda x: x.rolling(20).var()).fillna(0.0)
        return cov / (mkt_var + self.EPSILON)